import type { Player } from "../lib/types";

const mockAvatarLayers = JSON.stringify([
  { x: 5, y: 5, image: "/Img/Avatar/bodies/bd8_s1.png" },
  { x: 5, y: 5, image: "/Img/Avatar/faces/f7c.png" },
  { x: 19, y: -1, image: "/Img/Avatar/eyes/e14c.png" },
  { x: 28, y: 36, image: "/Img/Avatar/mouths/m33c.png" },
  { x: 14, y: 6, image: "/Img/Avatar/noses/n38.png" },
  { x: 5, y: 5, image: "/Img/Avatar/hair/f7h7e.png" },
]);

const basePlayer: Player = {
  id: 1,
  playerId: 100001,
  fetchedAt: "2026-04-05T12:00:00Z",
  firstName: "Carlos",
  nickName: "",
  lastName: "Rodriguez",
  playerNumber: 7,
  age: 22,
  ageDays: 45,
  tsi: 34500,
  playerForm: 7,
  experience: 6,
  loyalty: 8,
  motherClubBonus: false,
  leadership: 3,
  salary: 5200,
  isAbroad: false,
  specialty: 1,
  cards: 0,
  injuryLevel: -1,
  staminaSkill: 7,
  keeperSkill: 1,
  playmakerSkill: 9,
  scorerSkill: 5,
  passingSkill: 8,
  wingerSkill: 4,
  defenderSkill: 3,
  setPiecesSkill: 5,
  playerCategoryId: 5,
  transferListed: false,
  avatarBackground: "/Img/Avatar/backgrounds/bg_blue_int.png",
  avatarLayers: mockAvatarLayers,
  positionScores: { goalkeeper: 1.2, centralDefender: 4.5, wingBack: 3.8, innerMidfielder: 12.1, winger: 6.3, forward: 8.7 },
  positionOverride: null,
  recentChanges: [],
};

export const mockPlayers: Player[] = [
  basePlayer,
  {
    ...basePlayer,
    id: 2,
    playerId: 100002,
    firstName: "Manuel",
    lastName: "Neuer",
    playerNumber: 1,
    age: 25,
    ageDays: 12,
    tsi: 28000,
    playerForm: 6,
    specialty: 0,
    keeperSkill: 12,
    playmakerSkill: 2,
    scorerSkill: 1,
    passingSkill: 3,
    defenderSkill: 5,
    staminaSkill: 6,
    wingerSkill: 1,
    setPiecesSkill: 4,
    playerCategoryId: 1,
    recentChanges: [
      {
        id: 1,
        playerId: 100002,
        detectedAt: "2026-04-04T12:00:00Z",
        key: "keeperSkill",
        oldValue: "11",
        newValue: "12",
      },
    ],
  },
  {
    ...basePlayer,
    id: 3,
    playerId: 100003,
    firstName: "Diego",
    nickName: "El Toro",
    lastName: "Fernandez",
    playerNumber: 9,
    age: 28,
    ageDays: 80,
    tsi: 52000,
    playerForm: 8,
    specialty: 3,
    keeperSkill: 1,
    playmakerSkill: 5,
    scorerSkill: 14,
    passingSkill: 6,
    wingerSkill: 3,
    defenderSkill: 2,
    staminaSkill: 8,
    setPiecesSkill: 6,
    cards: 1,
    injuryLevel: 0,
    playerCategoryId: 6,
    recentChanges: [
      {
        id: 2,
        playerId: 100003,
        detectedAt: "2026-04-04T12:00:00Z",
        key: "scorerSkill",
        oldValue: "13",
        newValue: "14",
      },
      {
        id: 3,
        playerId: 100003,
        detectedAt: "2026-04-04T12:00:00Z",
        key: "staminaSkill",
        oldValue: "9",
        newValue: "8",
      },
    ],
  },
  {
    ...basePlayer,
    id: 4,
    playerId: 100004,
    firstName: "James",
    lastName: "Wilson",
    playerNumber: 4,
    age: 20,
    ageDays: 5,
    tsi: 15000,
    playerForm: 5,
    specialty: 0,
    keeperSkill: 1,
    playmakerSkill: 3,
    scorerSkill: 2,
    passingSkill: 4,
    wingerSkill: 2,
    defenderSkill: 9,
    staminaSkill: 7,
    setPiecesSkill: 3,
    injuryLevel: 2,
    playerCategoryId: 3,
    avatarBackground: "/Img/Avatar/backgrounds/bg_blue_int.png",
    avatarLayers: "[]",
    recentChanges: [],
  },
  {
    ...basePlayer,
    id: 5,
    playerId: 100005,
    firstName: "Luca",
    lastName: "Modric",
    playerNumber: 10,
    age: 24,
    ageDays: 66,
    tsi: 41000,
    playerForm: 7,
    specialty: 1,
    keeperSkill: 1,
    playmakerSkill: 12,
    scorerSkill: 4,
    passingSkill: 10,
    wingerSkill: 7,
    defenderSkill: 4,
    staminaSkill: 7,
    setPiecesSkill: 8,
    transferListed: true,
    playerCategoryId: 5,
    recentChanges: [
      {
        id: 4,
        playerId: 100005,
        detectedAt: "2026-04-04T12:00:00Z",
        key: "playmakerSkill",
        oldValue: "11",
        newValue: "12",
      },
    ],
  },
];
